- name: Write out haproxy config file
  template:
    src: ../templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy

- name: Open up firewall ports
  firewalld:
    permanent: yes
    immediate: yes
    state: enabled
    port: "{{ item }}"
  with_items:
    - 443/tcp
    - 80/tcp
    - 6443/tcp
    - 6443/udp
    - 22623/tcp
    - 22623/udp
    - 9000/tcp
    - 32700/tcp

- name: SEBool allow haproxy connect any port
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
  notify:
    - restart haproxy
