- name: Write out haproxy config file
  template:
    src: ../templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy

- name: Copy httpd conf file
  copy:
    src: ../files/httpd.conf
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - restart httpd
