- name: Write out named file
  template:
    src: ../templates/named.conf.j2
    dest: /etc/named.conf
  notify:
    - restart bind

- name: Installing DNS Serialnumber generator
  copy:
    src: ../files/set-dns-serial.sh
    dest: /usr/local/bin/set-dns-serial.sh
    mode: '0555'

- name: Set zone serial number
  shell: "/usr/local/bin/set-dns-serial.sh"
  register: dymanicserialnumber

- name: Setting serial number as a fact
  set_fact:
    serialnumber: "{{ dymanicserialnumber.stdout }}"

- name: Write out "{{ dns.domain }}" zone file
  template:
    src: ../templates/zonefile.j2
    dest: /var/named/zonefile.db
  notify:
    - restart bind

- name: Write out reverse zone file
  template:
    src: ../templates/reverse.j2
    dest: /var/named/reverse.db
  notify:
    - restart bind
