- name: Copy info script over
  template:
    src: ../templates/checker.sh.j2
    dest: /usr/local/bin/helpernodecheck
    owner: root
    group: root
    mode: 0555

- name: Downloading OCP4 client
  get_url:
    url: "{{ ocp_client }}"
    dest: /usr/local/src/openshift-client-linux.tar.gz

- name: Downloading OCP4 Installer
  get_url:
    url: "{{ ocp_installer }}"
    dest: /usr/local/src/openshift-install-linux.tar.gz

- name: Unarchiving OCP4 client
  unarchive:
    src: /usr/local/src/openshift-client-linux.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Unarchiving OCP4 Installer
  unarchive:
    src: /usr/local/src/openshift-install-linux.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Removing files that are not needed
  file:
    path: /usr/local/bin/README.md
    state: absent

- name: Downloading filetranspiler source
  git:
    repo: https://github.com/ashcrow/filetranspiler
    dest: /usr/local/src/filetranspiler

- name: Building filetranspiler
  shell: "podman build /usr/local/src/filetranspiler -t filetranspiler:latest"

- name: Installing filetranspiler
  copy:
    src: ../files/filetranspiler
    dest: /usr/local/bin/filetranspiler
    mode: '0555'

- name: Get network device system name
  shell: "nmcli -t dev show {{ helper.networkifacename }} | grep GENERAL.CONNECTION | cut -d: -f2"
  register: devicesystemname

- name: Setting network device system name as a fact
  set_fact:
    dsname: "{{ devicesystemname.stdout }}"
