- name: Install needed packages
  yum:
    name:
      - bind
      - bind-utils
      - haproxy
      - httpd
      - vim
      - bash-completion
      - libselinux-python
      - podman
      - nfs-utils
      - git
    state: present
