- name: Register as auto-subscribe to red hat subscription.
  redhat_subscription:
    state: present
    username: "{{ rhel_username }}"
    password: "{{ rhel_password }}"
    auto_attach: true

- name: Enable rhel-7-server-rpms repository
  rhsm_repository:
    name: rhel-7-server-rpms

- name: Enable rhel-7-server-extras-rpms repository
  rhsm_repository:
    name: rhel-7-server-extras-rpms
    state: enabled
